### ISSUE TITLE
Stop removing all spaces after save file

### ISSUE THREAD

**Issue by papilip** [crystal-lang-tools/sublime-crystal#20]
Hello,

When i save a file .cr
I tabulate my code with spaces, all of then are deleted.
```
var1   = "var1"
myvar2 = "myvar2"
```
=>
```
var1 = "var1"
myvar2 = "myvar2"
```
How to delete this action and move it to a function key.
Saving my code should not transforme my code silently, without permission !

**Comment by faustinoaq** [comment]
> How to delete this action and move it to a function key.

Is a crystal formatting convention, just constants, hashes and name tuples should be aligned.

**Comment by faultyserver** [comment]
You can also add `"auto_format": false` to your syntax-specific settings for Crystal to disable the automatic formatting when you save a file, e.g.:

```json
{
  "auto_format": false,
  "crystal_cmd": "crystal"
}
```

**Comment by papilip** [comment]
Thank both for solution and link.

**Comment by RX14** [comment]
We do recommend people still with the crystal formatter though, so that all crystal programs have a consistent style.
