### ISSUE TITLE
Block comment does not prefix empty line with `#`

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang-tools/sublime-crystal#22]
When applying a block comment, empty lines will not be prefixed with a `#`. This will tear the comment blocks apart.
I have no idea how to specify this in `preferences/Comments.tmPreferences`
followup on #21

**Comment by fgimian** [comment]
Hey @straight-shoota 😄 

I'm not actually sure if this is a problem per se.  I can see the same behaviour in C++, Ruby and Python using the default packages that come with Sublime Text 3, can you confirm?

I do agree it's a bit annoying though, but I think it's a Sublime Text feature request moreso than a big with this package.  I highly suspect this can't be adjusted from our end anyway.

Cheers
Fotis

**Comment by straight-shoota** [comment]
Yeah, that seems to be the case.
