### ISSUE TITLE
Auto Indent while saving doesn't worn on OS X

### ISSUE THREAD

**Issue by codenoid** [crystal-lang-tools/sublime-crystal#26]
working on my ubuntu, but not on my osx, sublime v 3, installed via packagecontrol,

**Comment by fgimian** [comment]
@codenoid Works perfectly here on macOS High Sierra.  Is the `crystal` executable in your PATH environment variable?

**Comment by codenoid** [comment]
i don't have mac right now

**Comment by fgimian** [comment]
Cool @codenoid, do you think we can close this issue for the moment then?  You're of course welcome to open a new one if you encounter the issue again and we can troubleshoot, but currently I can't replicate any such issue on my Mac.

Cheers
Fotis
