### ISSUE TITLE
Auto format on save not working on Windows 7/10

### ISSUE THREAD

**Issue by Dillybob1992** [crystal-lang-tools/sublime-crystal#34]
Auto formatting on CTRL+S was working fine on Linux Mint. However, I'm now using the unix sub system for Windows and the format doesn't seem to trigger on CTRL+S.
Stock installations of Sublime 3 and Crystal

**Comment by Dillybob1992** [comment]
Am getting
```
Traceback (most recent call last):
  File "./python3.3/subprocess.py", line 1104, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "crystal_format in C:\Users\Nick\AppData\Roaming\Sublime Text 3\Installed Packages\Crystal.sublime-package", line 30, in run
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

```

On save. I think this unix windows subsystem thing might be the root cause

**Comment by Dillybob1992** [comment]
I'm almost there with a solution

If you modify your sublime Crystal.sublime-settings to
```
  "crystal_cmd": "\"C:\\Users\\Nick\\Desktop\\bash.exe\" & crystal"
```
Assuming your editing a crystal file that's on your desktop,

The new bash console be initiated via coded, but gets *blocked* before it actually reads:
```
Traceback (most recent call last):
  File "./python3.3/subprocess.py", line 1104, in _execute_child
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "crystal_format in C:\Users\Nick\AppData\Roaming\Sublime Text 3\Installed Packages\Crystal.sublime-package", line 30, in run
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
PermissionError: [WinError 5] Access is denied
```

Weird... running as Administrator doesn't help at all (bash.exe, and sublime).

**Comment by faustinoaq** [comment]
I think you can try this:

```
 "crystal_cmd": "\"C:\\Users\\Nick\\Desktop\\bash.exe -c crystal\""
```

or (Windows 10 accepts `/` as well)

```
 "crystal_cmd": "C:/Users/Nick/Desktop/bash.exe -c crystal"
```

**Comment by faustinoaq** [comment]
Oh, Looks like  https://github.com/crystal-lang-tools/sublime-crystal/pull/19 solved this issue 👍

**Comment by Dillybob1992** [comment]
Hai @faustinoaq thanks for the help! Unfortunately

```
"crystal_cmd": "\"C:\\Users\\Nick\\Desktop\\bash.exe -c crystal\""
```

Gives me `PermissionError: [WinError 5] Access is denied`

and 
```
"crystal_cmd": "C:/Users/Nick/Desktop/bash.exe -c crystal"
````

gives: `FileNotFoundError: [WinError 2] The system cannot find the file specified`

I think the top one is the working path one, then now it gives a  permission error. Also I misread #19 sorry for getting too excited, that's for building and the not CTRL+S auto format.

I'm honestly stumped thank you for trying to help though :)

**Comment by Dillybob1992** [comment]
The JSON isn't being exported after `crystal tool format -f json` or the current way it's done in crystal_format.py, and it will result in:

```
ValueError: No JSON object could be decoded
```
Which is really good actually, because that means it's now being executed just no JSON export..

**Comment by Dillybob1992** [comment]
@faustinoaq Awesome, okay found a solution!

- Install https://github.com/faustinoaq/crystal-windows-installer
- Set `Crystal.sublime-settings` to:
```
{
  "auto_format": true,
  "crystal_cmd": "crystal.bat"
}
```

Starred the Crystal-windows-installer repo, fixed everything!
