### ISSUE TITLE
cmd popup on Sublime Text WIndows 10 + WSL

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang-tools/sublime-crystal#42]
![ezgif-1-e9165bf71d](https://user-images.githubusercontent.com/3067335/38469083-aa49a87a-3b14-11e8-8dbe-291bcfd5d0f5.gif)

This issue was discovered by @girng

Solution proposed by @oprypin :

1. We should replace this line:

https://github.com/crystal-lang-tools/sublime-crystal/blob/d4abc5ab4306ad13a7da2ec974ff927a2ff66bc2/crystal_format.py#L30

2. by something like this:

```python
            if operating_system == 'win':
                # Prevent flashing windows if used from a GUI application
                startupinfo = subprocess.STARTUPINFO()
                startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
                rc = subprocess.call(proc, stdout = pipe, stderr = pipe,
                                     startupinfo = startupinfo)
```

https://github.com/coin-or/pulp/blob/bac6d9d2214ba773d638d2de5149940cfd711359/src/pulp/solvers.py#L378-L382

**Comment by girng** [comment]
thank you my friend for posting this

**Comment by girng** [comment]
hi, thx for support again.

i got
`NameError: global name 'pipe' is not defined`
so i changed the `pipe` to `subprocess.PIPE`, error went away.
but now, am getting:
`NameError: global name 'proc' is not defined` on line 33

this is line 33:
`proc.stdin.write(bytes(src, 'UTF-8'))`

**Comment by faustinoaq** [comment]
@girng Looks like you should use `pipe = open(os.devnull, 'w')` instead, see:

https://github.com/coin-or/pulp/blob/bac6d9d2214ba773d638d2de5149940cfd711359/src/pulp/solvers.py#L376

**Comment by girng** [comment]
thank you, @faustinoaq did that. got rid of the pipe error, now still get:

`NameError: global name 'proc' is not defined` **line 38, in run**

line 38:
`proc.stdin.write(bytes(src, 'UTF-8'))`

**Comment by girng** [comment]
ty for continuing to help. this is painful xD

first code u supplied, i get:
> AttributeError: 'int' object has no attribute 'stdin' 
line 39:
`proc.stdin.write(bytes(src, 'UTF-8'))`

-------------------
2nd code u supplied, i get:
```
    return self.run(edit)
  File "crystal_format in C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Installed Packages\Crystal.sublime-package", line 38, in run
AttributeError: __exit__
```
line 38:
`with subprocess.call(cmd, stdout = pipe, stderr = pipe,startupinfo = startupinfo) as proc:`

**Comment by oprypin** [comment]
What a mess...
Please try #43

**Comment by faustinoaq** [comment]
@oprypin Thank you! :sweat_smile:

**Comment by girng** [comment]
File "crystal_format in C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Installed Packages\Crystal.sublime-package", line 45, in run
NameError: global name 'exit' is not defined

line 45:
`    if exit == 0:`

**Comment by girng** [comment]
ok, so i commented out the if exit == 0 block (got rid of that error). however, it doesn't format the code still :(

sorry for all the trouble, im just trying reporting back if errors are found

**Comment by girng** [comment]
ok. got it working

```
  def run(self, edit):
    vsize = self.view.size()
    region = sublime.Region(0, vsize)
    src = self.view.substr(region)
    window = self.view.window()

    settings = sublime.load_settings('Crystal.sublime-settings')
    command = [settings.get("crystal_cmd"), "tool", "format", "-", "--format", "json"]

    popen_args = dict(args=command, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
    # Prevent flashing terminal windows
    if sys.platform.startswith('win'):
      popen_args['startupinfo'] = subprocess.STARTUPINFO()
      popen_args['startupinfo'].dwFlags |= subprocess.STARTF_USESHOWWINDOW

    with subprocess.Popen(**popen_args) as proc:
      output, _ = proc.communicate(src.encode('utf-8'))
      output = output.decode('utf-8')

    pos = 0
    if not self.has_redo():
      for op, text in diff_match_patch().diff_main(src, output):
        if op == diff_match_patch.DIFF_DELETE:
          self.view.erase(edit, sublime.Region(pos, pos + len(text)))
        if op == diff_match_patch.DIFF_INSERT:
          self.view.insert(edit, pos, text)
          pos += len(text)
        if op == diff_match_patch.DIFF_EQUAL:
          pos += len(text)

      self.view.erase_regions('crystal_errors')
      window.run_command("hide_panel")

    else:
      error = json.loads(output)
      error_pos = self.view.text_point(error[0]["line"] - 1, error[0]["column"] - 1)
      line_region = self.view.full_line(error_pos)
      self.view.add_regions('crystal_errors', [line_region], 'comment', 'dot', sublime.HIDDEN)

      error_panel = window.create_output_panel('crystal_errors')
      error_panel.run_command("append", {"characters":
        "Error at line %d, column %d: %s" % (error[0]["line"], error[0]["column"], error[0]['message'])
      })
      window.run_command("show_panel", {"panel": "output.crystal_errors"})

```

i basically just removed the `if exit == 0:` from oprypin's code

**Comment by girng** [comment]
### WARNING

DO NOT REMOVE that if exit == 0

i just saved and almost my entire LoginHandler.cr file (it replaced my file with blank text). Doing a back up right now and going back to the original crystal_format.py with the cmd pop up for now.

**Comment by faustinoaq** [comment]
@girng No problem, keep trying, Thank you for be aware of this issue :+1:

**Comment by girng** [comment]
Praise to you and opryprin for help. just need solution for `global name 'exit' is not defined` and this can finally be solved!!

**Comment by oprypin** [comment]
Needs `exit = proc.returncode`
